
name: Draft Action for TriBITS

# Controls when the action will run. 
# Triggers the workflow on push or pull request
# for the master and develop branch 
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.7]
        cxx-compilers: [g++-9]

    steps:
    - uses: actions/checkout@v1

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}

    - name: Update environnement...
      run: |
        sudo apt-get update

    - name: Setup environnement...
      run: |
        PARENT_DIR=$(pwd)/..
        echo "WORKSPACE_PARENT_DIR=$PARENT_DIR" >> $GITHUB_ENV
        echo "SRC_DIR=${PARENT_DIR}/TriBITS" >> $GITHUB_ENV
        echo "BUILD_DIR=$PARENT_DIR/build" >> $GITHUB_ENV
        ${{ matrix.config.requirements }}
        ls $(pwd) 
    # - name: Build
    #   env:
    #     CXX: ${{matrix.cxx-compilers}}

    #   run: |
    #     echo "Compilers:"
    #     echo $CXX
    #     echo ${{ env.WORKSPACE_PARENT_DIR }}

    #     mkdir ${{ env.BUILD_DIR }} 
    #     cd ${{ env.BUILD_DIR }}
    #     cmake \
    #     -D TPL_ENABLE_MPI=OFF \
    #     -D CMAKE_C_COMPILER=$CC \
    #     -D TriBITS_ENABLE_Fortran=ON \
    #     -D TriBITS_ENABLE_TESTS=ON \
    #     ${{ env.WORKSPACE_PARENT_DIR }}/TriBITS
